# -*- coding: utf-8 -*-
"""PCA_Implementation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nxE1TZyc07iHY0c9kmo0jH4OtHAtI1PV
"""

import numpy as np
import matplotlib.pyplot as plt

m=50 # number of points
n=2  # R^n
l=1  #reduce to R^l
#random m point: X=(x_1,..., x_m)
X=np.random.randn(n,m) #randn

#X=[[1,2,3,4,5],[0,0,0,0,0]]
XT=np.transpose(X)

#M=X*X^T
M=X@XT

# decompose M=QDQ^T
eigen_vals, eigen_vec=np.linalg.eig(M)

#D=Q[:,:l] (l columns)
D=eigen_vec[:, :l]

#code D

#decode D^T

print(eigen_vec)


plt.scatter(X[0],X[1])

# Calculate points on the line using the eigenvector
t_values = np.linspace(-5,5, 100)  # Choose values of t to span the line
line_points = np.array([t*eigen_vec[:,0] for t in t_values])
plt.plot(line_points[:, 0], line_points[:, 1], label='Line', color='red')
